steps:
  - label: "Check Docker Registry"
    command: curl https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest -I -XGET -6
  - label: "check dns"
    command: dig ANY +noall +answer registry.docker.io
  - label: "Download img"
    command: docker pull ubuntu:xenial
  - label: "Download img ipv4"
    command: echo "34.205.13.154 registry.docker.io >> /etc/hosts" && echo "34.205.13.154 registry-1.docker.io >> /etc/hosts" && docker pull ubuntu:xenial
